CREATE TABLE IF NOT EXISTS departments(
	department_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	department_name text NOT NULL,
	address text,
	chief_fio text,
	activity_type text
);
CREATE TABLE IF NOT EXISTS staff(
	staff_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	fio text NOT NULL,
	position_name text,
	is_work boolean NOT NULL DEFAULT False,
	department_id int NOT NULL REFERENCES departments(department_id)
);
CREATE TABLE IF NOT EXISTS pass(
	pass_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	issue_date date NOT NULL,
	expiration_date date NOT NULL DEFAULT CURRENT_DATE,
	staff_id int NOT NULL REFERENCES staff(staff_id),
	pass_department_id int NOT NULL REFERENCES departments(department_id)
);
CREATE TABLE IF NOT EXISTS access_groups(
	group_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	group_name text NOT NULL,
	change_date date NOT NULL
);
CREATE TABLE IF NOT EXISTS purpose(
	purpose_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	issue_date date NOT NULL,
	expiration_date date NOT NULL DEFAULT CURRENT_DATE,
	pass_id int NOT NULL REFERENCES pass(pass_id),
	group_id int NOT NULL REFERENCES access_groups(group_id)
);
CREATE TABLE IF NOT EXISTS access_controller(
	controller_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	object_name text NOT NULL,
	address text,
	work_shedule text,
	network_address text NOT NULL,
	model text,
	status text NOT NULL CHECK (status IN('Online', 'Offline','Restarting')) DEFAULT 'Offline'
);
CREATE TABLE IF NOT EXISTS group_consists(
	position_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	controller_id int NOT NULL REFERENCES access_controller(controller_id),
	group_id int NOT NULL REFERENCES access_groups(group_id)
);
CREATE TABLE IF NOT EXISTS access_facts(
	access_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	solution text NOT NULL CHECK (solution IN('Rejected', 'Accepted','Pending')) DEFAULT 'Pending',
	access_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	access_type text NOT NULL CHECK (access_type IN('IN', 'OUT')),
	pass_id int NOT NULL REFERENCES pass(pass_id),
	controller_id int NOT NULL REFERENCES access_controller(controller_id)
);
CREATE TABLE IF NOT EXISTS users(
	user_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	login text NOT NULL,
	passphrase text NOT NULL,
	user_role text NOT NULL CHECK (user_role IN('Admin', 'Controller','HR','PD'))
);