CREATE TABLE IF NOT EXISTS departments(
	department_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	department_name text NOT NULL,
	address text NOT NULL,
	chief_fio text,
	activity_type text
);
ALTER TABLE departments ADD CONSTRAINT unique_department UNIQUE (department_name, address);
CREATE TABLE IF NOT EXISTS staff(
	staff_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	fio text NOT NULL,
    phone text NOT NULL UNIQUE,
	position_name text,
	is_work boolean NOT NULL DEFAULT False,
	department_id int NOT NULL REFERENCES departments(department_id)
);
CREATE TABLE IF NOT EXISTS pass(
	pass_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	issue_date date NOT NULL,
	expiration_date date NOT NULL DEFAULT CURRENT_DATE,
	staff_id int NOT NULL REFERENCES staff(staff_id),
	pass_department_id int NOT NULL REFERENCES departments(department_id)
);
CREATE TABLE IF NOT EXISTS access_groups(
	group_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	group_name text NOT NULL UNIQUE,
	change_date date NOT NULL
);
CREATE TABLE IF NOT EXISTS purpose(
	purpose_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	issue_date date NOT NULL,
	expiration_date date NOT NULL DEFAULT CURRENT_DATE,
	pass_id int NOT NULL REFERENCES pass(pass_id),
	group_id int NOT NULL REFERENCES access_groups(group_id)
);
CREATE TABLE IF NOT EXISTS access_controller(
	controller_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	object_name text NOT NULL,
	address text,
	work_shedule text,
	network_address text NOT NULL,
	model text,
	status text NOT NULL CHECK (status IN('Online', 'Offline','Restarting')) DEFAULT 'Offline'
);
ALTER TABLE access_controller ADD CONSTRAINT unique_object_address UNIQUE (object_name, address);
CREATE TABLE IF NOT EXISTS group_consists(
	position_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	controller_id int NOT NULL REFERENCES access_controller(controller_id),
	group_id int NOT NULL REFERENCES access_groups(group_id)
);
CREATE TABLE IF NOT EXISTS access_facts(
	access_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	solution text NOT NULL CHECK (solution IN('Rejected', 'Accepted','Pending')) DEFAULT 'Pending',
	access_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	access_type text NOT NULL CHECK (access_type IN('IN', 'OUT')),
	pass_id int NOT NULL REFERENCES pass(pass_id),
	controller_id int NOT NULL REFERENCES access_controller(controller_id)
); 
CREATE TABLE IF NOT EXISTS users(
	user_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	login text NOT NULL,
	passphrase text NOT NULL,
	user_role text NOT NULL CHECK (user_role IN('Admin', 'Controller','HR','PD'))
);

CREATE OR REPLACE FUNCTION delete_staff_cascade()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM pass WHERE staff_id = OLD.staff_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_delete_staff_cascade
BEFORE DELETE ON staff
FOR EACH ROW
EXECUTE FUNCTION delete_staff_cascade();

-- 2. Каскадное удаление при удалении pass
CREATE OR REPLACE FUNCTION delete_pass_cascade()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM purpose WHERE pass_id = OLD.pass_id;
    DELETE FROM access_facts WHERE pass_id = OLD.pass_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_delete_pass_cascade
BEFORE DELETE ON pass
FOR EACH ROW
EXECUTE FUNCTION delete_pass_cascade();

-- 3. Каскадное удаление при удалении access_groups
CREATE OR REPLACE FUNCTION delete_access_groups_cascade()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM purpose WHERE group_id = OLD.group_id;
    DELETE FROM group_consists WHERE group_id = OLD.group_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_delete_access_groups_cascade
BEFORE DELETE ON access_groups
FOR EACH ROW
EXECUTE FUNCTION delete_access_groups_cascade();

-- 4. Каскадное удаление при удалении access_controller
CREATE OR REPLACE FUNCTION delete_access_controller_cascade()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM access_facts WHERE controller_id = OLD.controller_id;
    DELETE FROM group_consists WHERE controller_id = OLD.controller_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_delete_access_controller_cascade
BEFORE DELETE ON access_controller
FOR EACH ROW
EXECUTE FUNCTION delete_access_controller_cascade();

-- 5. Каскадное удаление при удалении departments
CREATE OR REPLACE FUNCTION delete_departments_cascade()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM pass WHERE pass_department_id = OLD.department_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_delete_departments_cascade
BEFORE DELETE ON departments
FOR EACH ROW
EXECUTE FUNCTION delete_departments_cascade();
